### ISSUE TITLE
AES GCM is broken

### ISSUE THREAD

**Issue by alippai** [vibornoff/asmcrypto.js#70]
I have several failing test cases, will investigate it tomorrow. Maybe it's nonce length related (eg. one byte long nonce), don't know it yet.

The same input was provided for webcrypto and asmcrypto, that's all I've got now.

**Comment by alippai** [comment]
E.g. if additional data is null and nonce is 1 byte long, it fails. We'll add a large test suite for this (generated with openssl).

**Comment by vibornoff** [comment]
Ok, great thanks, I'll fix this issue ASAP.

**Comment by vibornoff** [comment]
Seems fixed now.

**Comment by pohutukawa** [comment]
Interesting, indeed. I have just upgraded our version to tag `v0.0.9` and surely AES-GCM works as expected.

However ... now AES-CCM misbehaves:

I'm not able to use it to encrypt or decrypt any content without passing in *anything* for the `adata` parameter. I believe that the GCM implementation is behaving there properly, but the CCM implementation is off. It looks like the culprit is `AES_CCM_reset`. The GCM implementation equivalent here has a different conditional in the outer `if` statement for the `adata` field check. The function also checks for a value of `iv`, which is not a parameter for CCM, but rather `nonce` takes that place, which is providing a start for the counter. So, as `iv` *and* `adata` are missing, it is throwing an exception in *every* case without `adata`.

I know, this is a different issue (as opposed to the one I've opened here), but I'm just hesitant to open a new issue for this to keep the discussion flowing on this one ticket.

Again, some test code:

```javascript
var adataCases = [undefined, null, '', new Uint8Array()];
var key = asmCrypto.string_to_bytes(atob('dGQhii+B7+eLLHRiOA690w=='));
var nonce = asmCrypto.string_to_bytes(atob('R8q1njARXS7urWv3'));
var plainText = atob('dGQhwoovwoHDr8OnwossdGI4DsK9w5M=');
for (var i = 0; i < adataCases.length; i++) {
    var result = asmCrypto.AES_CCM.encrypt(plainText, key, nonce, adataCases[i], 16);
}
```
