### ISSUE TITLE
password,data   data,password 

### ISSUE THREAD

**Issue by sentient** [vibornoff/asmcrypto.js#71]
documentation (https://github.com/vibornoff/asmcrypto.js#hmac_sha256)
says

HMAC_SHA256.base64( password, data )

But code is :

function hmac_sha256_base64 ( data, password ) {
    var result = hmac_sha256_bytes( data, password );
    return bytes_to_base64(result);
}

Following code seems to be correct, is the documentation outdated?

**Comment by vibornoff** [comment]
Yep, documentation is outdated. Thanks a lot for paying attention.

**Comment by pohutukawa** [comment]
Yes, this has also just cost me half a day in tracking down the problem. I only figured it out after checking the source. I just wanted to report it, when seeing that there was a ticket on it already.
All the HMAC functions' documentation is "out of whack" with regards to this.

Wouldn't it make sense to use JSDoc strings for the implementations in the source code. That way stuff like that would more easily be found at the time of development, and the actual documentation then can be generated mechanically rather than having to write and maintain it manually?

**Comment by pohutukawa** [comment]
On another note: There are also no unit tests for the HMAC implementations.
